# Generated by Django 4.0.3 on 2022-03-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_userinfo_host_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='opponent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
