# Generated by Django 4.0.3 on 2022-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0006_room_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='word',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
